FROM openjdk:8-jre-alpine

ARG PIPELINE_NAME
ARG GROUP_NAME
ARG OUTGOING_TOPIC_NAME
ARG ERROR_TOPIC_NAME
ARG KAFKA_BROKERS
ARG STORAGE_URL
ARG INDEXING_URL
ARG POLL_INTERVAL_MILLIS
ARG S3_BUCKET_NAME
ARG S3_ACCESS_KEY
ARG S3_SECRET
ARG S3_INCOMING_PREFIX
ARG S3_PROCESSED_PREFIX

ENV PIPELINE_NAME ${PROFILE_NAME}
ENV GROUP_NAME ${GROUP_NAME}
ENV OUTGOING_TOPIC_NAME ${OUTGOING_TOPIC_NAME}
ENV ERROR_TOPIC_NAME ${ERROR_TOPIC_NAME}
ENV KAFKA_BROKERS ${KAFKA_BROKERS}
ENV STORAGE_URL ${STORAGE_URL}
ENV INDEXING_URL ${INDEXING_URL}
ENV POLL_INTERVAL_MILLIS ${POLL_INTERVAL_MILLIS}
ENV S3_BUCKET_NAME ${S3_BUCKET_NAME}
ENV S3_ACCESS_KEY ${S3_ACCESS_KEY}
ENV S3_SECRET ${S3_SECRET}
ENV S3_INCOMING_PREFIX ${S3_INCOMING_PREFIX}
ENV S3_PROCESSED_PREFIX ${S3_PROCESSED_PREFIX}

COPY target/s3-source-producer-*-jar-with-dependencies.jar /app.jar
ENTRYPOINT java -jar /app.jar
