/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.cdc.ncezid.eip.ds.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FDDEIPSource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1379811936842067099L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FDDEIPSource\",\"namespace\":\"gov.cdc.ncezid.eip.ds.schema\",\"fields\":[{\"name\":\"messageGUID\",\"type\":\"string\",\"default\":null},{\"name\":\"transportGUID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bhsGUID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"batchPosition\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"fhsGUID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"sender\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"condition\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"messageCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"triggerEvent\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"messageStructure\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"profile\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"versionId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"createdBy\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"createdTime\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"updatedBy\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"updatedTime\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"content\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"md5\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FDDEIPSource> ENCODER =
      new BinaryMessageEncoder<FDDEIPSource>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FDDEIPSource> DECODER =
      new BinaryMessageDecoder<FDDEIPSource>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FDDEIPSource> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FDDEIPSource> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FDDEIPSource>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FDDEIPSource to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FDDEIPSource from a ByteBuffer. */
  public static FDDEIPSource fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence messageGUID;
  @Deprecated public java.lang.CharSequence transportGUID;
  @Deprecated public java.lang.CharSequence bhsGUID;
  @Deprecated public java.lang.Long batchPosition;
  @Deprecated public java.lang.CharSequence fhsGUID;
  @Deprecated public java.lang.CharSequence status;
  @Deprecated public java.lang.CharSequence sender;
  @Deprecated public java.lang.CharSequence condition;
  @Deprecated public java.lang.CharSequence messageCode;
  @Deprecated public java.lang.CharSequence triggerEvent;
  @Deprecated public java.lang.CharSequence messageStructure;
  @Deprecated public java.lang.CharSequence profile;
  @Deprecated public java.lang.CharSequence versionId;
  @Deprecated public java.lang.CharSequence createdBy;
  @Deprecated public java.lang.Long createdTime;
  @Deprecated public java.lang.CharSequence updatedBy;
  @Deprecated public java.lang.Long updatedTime;
  @Deprecated public java.lang.CharSequence content;
  @Deprecated public java.lang.CharSequence md5;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FDDEIPSource() {}

  /**
   * All-args constructor.
   * @param messageGUID The new value for messageGUID
   * @param transportGUID The new value for transportGUID
   * @param bhsGUID The new value for bhsGUID
   * @param batchPosition The new value for batchPosition
   * @param fhsGUID The new value for fhsGUID
   * @param status The new value for status
   * @param sender The new value for sender
   * @param condition The new value for condition
   * @param messageCode The new value for messageCode
   * @param triggerEvent The new value for triggerEvent
   * @param messageStructure The new value for messageStructure
   * @param profile The new value for profile
   * @param versionId The new value for versionId
   * @param createdBy The new value for createdBy
   * @param createdTime The new value for createdTime
   * @param updatedBy The new value for updatedBy
   * @param updatedTime The new value for updatedTime
   * @param content The new value for content
   * @param md5 The new value for md5
   */
  public FDDEIPSource(java.lang.CharSequence messageGUID, java.lang.CharSequence transportGUID, java.lang.CharSequence bhsGUID, java.lang.Long batchPosition, java.lang.CharSequence fhsGUID, java.lang.CharSequence status, java.lang.CharSequence sender, java.lang.CharSequence condition, java.lang.CharSequence messageCode, java.lang.CharSequence triggerEvent, java.lang.CharSequence messageStructure, java.lang.CharSequence profile, java.lang.CharSequence versionId, java.lang.CharSequence createdBy, java.lang.Long createdTime, java.lang.CharSequence updatedBy, java.lang.Long updatedTime, java.lang.CharSequence content, java.lang.CharSequence md5) {
    this.messageGUID = messageGUID;
    this.transportGUID = transportGUID;
    this.bhsGUID = bhsGUID;
    this.batchPosition = batchPosition;
    this.fhsGUID = fhsGUID;
    this.status = status;
    this.sender = sender;
    this.condition = condition;
    this.messageCode = messageCode;
    this.triggerEvent = triggerEvent;
    this.messageStructure = messageStructure;
    this.profile = profile;
    this.versionId = versionId;
    this.createdBy = createdBy;
    this.createdTime = createdTime;
    this.updatedBy = updatedBy;
    this.updatedTime = updatedTime;
    this.content = content;
    this.md5 = md5;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageGUID;
    case 1: return transportGUID;
    case 2: return bhsGUID;
    case 3: return batchPosition;
    case 4: return fhsGUID;
    case 5: return status;
    case 6: return sender;
    case 7: return condition;
    case 8: return messageCode;
    case 9: return triggerEvent;
    case 10: return messageStructure;
    case 11: return profile;
    case 12: return versionId;
    case 13: return createdBy;
    case 14: return createdTime;
    case 15: return updatedBy;
    case 16: return updatedTime;
    case 17: return content;
    case 18: return md5;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageGUID = (java.lang.CharSequence)value$; break;
    case 1: transportGUID = (java.lang.CharSequence)value$; break;
    case 2: bhsGUID = (java.lang.CharSequence)value$; break;
    case 3: batchPosition = (java.lang.Long)value$; break;
    case 4: fhsGUID = (java.lang.CharSequence)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    case 6: sender = (java.lang.CharSequence)value$; break;
    case 7: condition = (java.lang.CharSequence)value$; break;
    case 8: messageCode = (java.lang.CharSequence)value$; break;
    case 9: triggerEvent = (java.lang.CharSequence)value$; break;
    case 10: messageStructure = (java.lang.CharSequence)value$; break;
    case 11: profile = (java.lang.CharSequence)value$; break;
    case 12: versionId = (java.lang.CharSequence)value$; break;
    case 13: createdBy = (java.lang.CharSequence)value$; break;
    case 14: createdTime = (java.lang.Long)value$; break;
    case 15: updatedBy = (java.lang.CharSequence)value$; break;
    case 16: updatedTime = (java.lang.Long)value$; break;
    case 17: content = (java.lang.CharSequence)value$; break;
    case 18: md5 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messageGUID' field.
   * @return The value of the 'messageGUID' field.
   */
  public java.lang.CharSequence getMessageGUID() {
    return messageGUID;
  }

  /**
   * Sets the value of the 'messageGUID' field.
   * @param value the value to set.
   */
  public void setMessageGUID(java.lang.CharSequence value) {
    this.messageGUID = value;
  }

  /**
   * Gets the value of the 'transportGUID' field.
   * @return The value of the 'transportGUID' field.
   */
  public java.lang.CharSequence getTransportGUID() {
    return transportGUID;
  }

  /**
   * Sets the value of the 'transportGUID' field.
   * @param value the value to set.
   */
  public void setTransportGUID(java.lang.CharSequence value) {
    this.transportGUID = value;
  }

  /**
   * Gets the value of the 'bhsGUID' field.
   * @return The value of the 'bhsGUID' field.
   */
  public java.lang.CharSequence getBhsGUID() {
    return bhsGUID;
  }

  /**
   * Sets the value of the 'bhsGUID' field.
   * @param value the value to set.
   */
  public void setBhsGUID(java.lang.CharSequence value) {
    this.bhsGUID = value;
  }

  /**
   * Gets the value of the 'batchPosition' field.
   * @return The value of the 'batchPosition' field.
   */
  public java.lang.Long getBatchPosition() {
    return batchPosition;
  }

  /**
   * Sets the value of the 'batchPosition' field.
   * @param value the value to set.
   */
  public void setBatchPosition(java.lang.Long value) {
    this.batchPosition = value;
  }

  /**
   * Gets the value of the 'fhsGUID' field.
   * @return The value of the 'fhsGUID' field.
   */
  public java.lang.CharSequence getFhsGUID() {
    return fhsGUID;
  }

  /**
   * Sets the value of the 'fhsGUID' field.
   * @param value the value to set.
   */
  public void setFhsGUID(java.lang.CharSequence value) {
    this.fhsGUID = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'sender' field.
   * @return The value of the 'sender' field.
   */
  public java.lang.CharSequence getSender() {
    return sender;
  }

  /**
   * Sets the value of the 'sender' field.
   * @param value the value to set.
   */
  public void setSender(java.lang.CharSequence value) {
    this.sender = value;
  }

  /**
   * Gets the value of the 'condition' field.
   * @return The value of the 'condition' field.
   */
  public java.lang.CharSequence getCondition() {
    return condition;
  }

  /**
   * Sets the value of the 'condition' field.
   * @param value the value to set.
   */
  public void setCondition(java.lang.CharSequence value) {
    this.condition = value;
  }

  /**
   * Gets the value of the 'messageCode' field.
   * @return The value of the 'messageCode' field.
   */
  public java.lang.CharSequence getMessageCode() {
    return messageCode;
  }

  /**
   * Sets the value of the 'messageCode' field.
   * @param value the value to set.
   */
  public void setMessageCode(java.lang.CharSequence value) {
    this.messageCode = value;
  }

  /**
   * Gets the value of the 'triggerEvent' field.
   * @return The value of the 'triggerEvent' field.
   */
  public java.lang.CharSequence getTriggerEvent() {
    return triggerEvent;
  }

  /**
   * Sets the value of the 'triggerEvent' field.
   * @param value the value to set.
   */
  public void setTriggerEvent(java.lang.CharSequence value) {
    this.triggerEvent = value;
  }

  /**
   * Gets the value of the 'messageStructure' field.
   * @return The value of the 'messageStructure' field.
   */
  public java.lang.CharSequence getMessageStructure() {
    return messageStructure;
  }

  /**
   * Sets the value of the 'messageStructure' field.
   * @param value the value to set.
   */
  public void setMessageStructure(java.lang.CharSequence value) {
    this.messageStructure = value;
  }

  /**
   * Gets the value of the 'profile' field.
   * @return The value of the 'profile' field.
   */
  public java.lang.CharSequence getProfile() {
    return profile;
  }

  /**
   * Sets the value of the 'profile' field.
   * @param value the value to set.
   */
  public void setProfile(java.lang.CharSequence value) {
    this.profile = value;
  }

  /**
   * Gets the value of the 'versionId' field.
   * @return The value of the 'versionId' field.
   */
  public java.lang.CharSequence getVersionId() {
    return versionId;
  }

  /**
   * Sets the value of the 'versionId' field.
   * @param value the value to set.
   */
  public void setVersionId(java.lang.CharSequence value) {
    this.versionId = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.CharSequence getCreatedBy() {
    return createdBy;
  }

  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.CharSequence value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'createdTime' field.
   * @return The value of the 'createdTime' field.
   */
  public java.lang.Long getCreatedTime() {
    return createdTime;
  }

  /**
   * Sets the value of the 'createdTime' field.
   * @param value the value to set.
   */
  public void setCreatedTime(java.lang.Long value) {
    this.createdTime = value;
  }

  /**
   * Gets the value of the 'updatedBy' field.
   * @return The value of the 'updatedBy' field.
   */
  public java.lang.CharSequence getUpdatedBy() {
    return updatedBy;
  }

  /**
   * Sets the value of the 'updatedBy' field.
   * @param value the value to set.
   */
  public void setUpdatedBy(java.lang.CharSequence value) {
    this.updatedBy = value;
  }

  /**
   * Gets the value of the 'updatedTime' field.
   * @return The value of the 'updatedTime' field.
   */
  public java.lang.Long getUpdatedTime() {
    return updatedTime;
  }

  /**
   * Sets the value of the 'updatedTime' field.
   * @param value the value to set.
   */
  public void setUpdatedTime(java.lang.Long value) {
    this.updatedTime = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'md5' field.
   * @return The value of the 'md5' field.
   */
  public java.lang.CharSequence getMd5() {
    return md5;
  }

  /**
   * Sets the value of the 'md5' field.
   * @param value the value to set.
   */
  public void setMd5(java.lang.CharSequence value) {
    this.md5 = value;
  }

  /**
   * Creates a new FDDEIPSource RecordBuilder.
   * @return A new FDDEIPSource RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder newBuilder() {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder();
  }

  /**
   * Creates a new FDDEIPSource RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FDDEIPSource RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder newBuilder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder other) {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder(other);
  }

  /**
   * Creates a new FDDEIPSource RecordBuilder by copying an existing FDDEIPSource instance.
   * @param other The existing instance to copy.
   * @return A new FDDEIPSource RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder newBuilder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSource other) {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder(other);
  }

  /**
   * RecordBuilder for FDDEIPSource instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FDDEIPSource>
    implements org.apache.avro.data.RecordBuilder<FDDEIPSource> {

    private java.lang.CharSequence messageGUID;
    private java.lang.CharSequence transportGUID;
    private java.lang.CharSequence bhsGUID;
    private java.lang.Long batchPosition;
    private java.lang.CharSequence fhsGUID;
    private java.lang.CharSequence status;
    private java.lang.CharSequence sender;
    private java.lang.CharSequence condition;
    private java.lang.CharSequence messageCode;
    private java.lang.CharSequence triggerEvent;
    private java.lang.CharSequence messageStructure;
    private java.lang.CharSequence profile;
    private java.lang.CharSequence versionId;
    private java.lang.CharSequence createdBy;
    private java.lang.Long createdTime;
    private java.lang.CharSequence updatedBy;
    private java.lang.Long updatedTime;
    private java.lang.CharSequence content;
    private java.lang.CharSequence md5;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transportGUID)) {
        this.transportGUID = data().deepCopy(fields()[1].schema(), other.transportGUID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bhsGUID)) {
        this.bhsGUID = data().deepCopy(fields()[2].schema(), other.bhsGUID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.batchPosition)) {
        this.batchPosition = data().deepCopy(fields()[3].schema(), other.batchPosition);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fhsGUID)) {
        this.fhsGUID = data().deepCopy(fields()[4].schema(), other.fhsGUID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.sender)) {
        this.sender = data().deepCopy(fields()[6].schema(), other.sender);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.condition)) {
        this.condition = data().deepCopy(fields()[7].schema(), other.condition);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.messageCode)) {
        this.messageCode = data().deepCopy(fields()[8].schema(), other.messageCode);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.triggerEvent)) {
        this.triggerEvent = data().deepCopy(fields()[9].schema(), other.triggerEvent);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.messageStructure)) {
        this.messageStructure = data().deepCopy(fields()[10].schema(), other.messageStructure);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.profile)) {
        this.profile = data().deepCopy(fields()[11].schema(), other.profile);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.versionId)) {
        this.versionId = data().deepCopy(fields()[12].schema(), other.versionId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[13].schema(), other.createdBy);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.createdTime)) {
        this.createdTime = data().deepCopy(fields()[14].schema(), other.createdTime);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.updatedBy)) {
        this.updatedBy = data().deepCopy(fields()[15].schema(), other.updatedBy);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.updatedTime)) {
        this.updatedTime = data().deepCopy(fields()[16].schema(), other.updatedTime);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.content)) {
        this.content = data().deepCopy(fields()[17].schema(), other.content);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.md5)) {
        this.md5 = data().deepCopy(fields()[18].schema(), other.md5);
        fieldSetFlags()[18] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FDDEIPSource instance
     * @param other The existing instance to copy.
     */
    private Builder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSource other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transportGUID)) {
        this.transportGUID = data().deepCopy(fields()[1].schema(), other.transportGUID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bhsGUID)) {
        this.bhsGUID = data().deepCopy(fields()[2].schema(), other.bhsGUID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.batchPosition)) {
        this.batchPosition = data().deepCopy(fields()[3].schema(), other.batchPosition);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fhsGUID)) {
        this.fhsGUID = data().deepCopy(fields()[4].schema(), other.fhsGUID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.sender)) {
        this.sender = data().deepCopy(fields()[6].schema(), other.sender);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.condition)) {
        this.condition = data().deepCopy(fields()[7].schema(), other.condition);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.messageCode)) {
        this.messageCode = data().deepCopy(fields()[8].schema(), other.messageCode);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.triggerEvent)) {
        this.triggerEvent = data().deepCopy(fields()[9].schema(), other.triggerEvent);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.messageStructure)) {
        this.messageStructure = data().deepCopy(fields()[10].schema(), other.messageStructure);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.profile)) {
        this.profile = data().deepCopy(fields()[11].schema(), other.profile);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.versionId)) {
        this.versionId = data().deepCopy(fields()[12].schema(), other.versionId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[13].schema(), other.createdBy);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.createdTime)) {
        this.createdTime = data().deepCopy(fields()[14].schema(), other.createdTime);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.updatedBy)) {
        this.updatedBy = data().deepCopy(fields()[15].schema(), other.updatedBy);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.updatedTime)) {
        this.updatedTime = data().deepCopy(fields()[16].schema(), other.updatedTime);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.content)) {
        this.content = data().deepCopy(fields()[17].schema(), other.content);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.md5)) {
        this.md5 = data().deepCopy(fields()[18].schema(), other.md5);
        fieldSetFlags()[18] = true;
      }
    }

    /**
      * Gets the value of the 'messageGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageGUID() {
      return messageGUID;
    }

    /**
      * Sets the value of the 'messageGUID' field.
      * @param value The value of 'messageGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setMessageGUID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.messageGUID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageGUID' field has been set.
      * @return True if the 'messageGUID' field has been set, false otherwise.
      */
    public boolean hasMessageGUID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearMessageGUID() {
      messageGUID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transportGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransportGUID() {
      return transportGUID;
    }

    /**
      * Sets the value of the 'transportGUID' field.
      * @param value The value of 'transportGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setTransportGUID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.transportGUID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transportGUID' field has been set.
      * @return True if the 'transportGUID' field has been set, false otherwise.
      */
    public boolean hasTransportGUID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transportGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearTransportGUID() {
      transportGUID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bhsGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getBhsGUID() {
      return bhsGUID;
    }

    /**
      * Sets the value of the 'bhsGUID' field.
      * @param value The value of 'bhsGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setBhsGUID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bhsGUID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bhsGUID' field has been set.
      * @return True if the 'bhsGUID' field has been set, false otherwise.
      */
    public boolean hasBhsGUID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bhsGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearBhsGUID() {
      bhsGUID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'batchPosition' field.
      * @return The value.
      */
    public java.lang.Long getBatchPosition() {
      return batchPosition;
    }

    /**
      * Sets the value of the 'batchPosition' field.
      * @param value The value of 'batchPosition'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setBatchPosition(java.lang.Long value) {
      validate(fields()[3], value);
      this.batchPosition = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'batchPosition' field has been set.
      * @return True if the 'batchPosition' field has been set, false otherwise.
      */
    public boolean hasBatchPosition() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'batchPosition' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearBatchPosition() {
      batchPosition = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'fhsGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getFhsGUID() {
      return fhsGUID;
    }

    /**
      * Sets the value of the 'fhsGUID' field.
      * @param value The value of 'fhsGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setFhsGUID(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.fhsGUID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'fhsGUID' field has been set.
      * @return True if the 'fhsGUID' field has been set, false otherwise.
      */
    public boolean hasFhsGUID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'fhsGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearFhsGUID() {
      fhsGUID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'sender' field.
      * @return The value.
      */
    public java.lang.CharSequence getSender() {
      return sender;
    }

    /**
      * Sets the value of the 'sender' field.
      * @param value The value of 'sender'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setSender(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.sender = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'sender' field has been set.
      * @return True if the 'sender' field has been set, false otherwise.
      */
    public boolean hasSender() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'sender' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearSender() {
      sender = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'condition' field.
      * @return The value.
      */
    public java.lang.CharSequence getCondition() {
      return condition;
    }

    /**
      * Sets the value of the 'condition' field.
      * @param value The value of 'condition'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setCondition(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.condition = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'condition' field has been set.
      * @return True if the 'condition' field has been set, false otherwise.
      */
    public boolean hasCondition() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'condition' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearCondition() {
      condition = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageCode() {
      return messageCode;
    }

    /**
      * Sets the value of the 'messageCode' field.
      * @param value The value of 'messageCode'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setMessageCode(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.messageCode = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'messageCode' field has been set.
      * @return True if the 'messageCode' field has been set, false otherwise.
      */
    public boolean hasMessageCode() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'messageCode' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearMessageCode() {
      messageCode = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'triggerEvent' field.
      * @return The value.
      */
    public java.lang.CharSequence getTriggerEvent() {
      return triggerEvent;
    }

    /**
      * Sets the value of the 'triggerEvent' field.
      * @param value The value of 'triggerEvent'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setTriggerEvent(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.triggerEvent = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'triggerEvent' field has been set.
      * @return True if the 'triggerEvent' field has been set, false otherwise.
      */
    public boolean hasTriggerEvent() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'triggerEvent' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearTriggerEvent() {
      triggerEvent = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageStructure' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageStructure() {
      return messageStructure;
    }

    /**
      * Sets the value of the 'messageStructure' field.
      * @param value The value of 'messageStructure'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setMessageStructure(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.messageStructure = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'messageStructure' field has been set.
      * @return True if the 'messageStructure' field has been set, false otherwise.
      */
    public boolean hasMessageStructure() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'messageStructure' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearMessageStructure() {
      messageStructure = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'profile' field.
      * @return The value.
      */
    public java.lang.CharSequence getProfile() {
      return profile;
    }

    /**
      * Sets the value of the 'profile' field.
      * @param value The value of 'profile'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setProfile(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.profile = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'profile' field has been set.
      * @return True if the 'profile' field has been set, false otherwise.
      */
    public boolean hasProfile() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'profile' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearProfile() {
      profile = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'versionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getVersionId() {
      return versionId;
    }

    /**
      * Sets the value of the 'versionId' field.
      * @param value The value of 'versionId'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setVersionId(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.versionId = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'versionId' field has been set.
      * @return True if the 'versionId' field has been set, false otherwise.
      */
    public boolean hasVersionId() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'versionId' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearVersionId() {
      versionId = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedBy() {
      return createdBy;
    }

    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setCreatedBy(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.createdBy = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdTime' field.
      * @return The value.
      */
    public java.lang.Long getCreatedTime() {
      return createdTime;
    }

    /**
      * Sets the value of the 'createdTime' field.
      * @param value The value of 'createdTime'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setCreatedTime(java.lang.Long value) {
      validate(fields()[14], value);
      this.createdTime = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'createdTime' field has been set.
      * @return True if the 'createdTime' field has been set, false otherwise.
      */
    public boolean hasCreatedTime() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'createdTime' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearCreatedTime() {
      createdTime = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedBy' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedBy() {
      return updatedBy;
    }

    /**
      * Sets the value of the 'updatedBy' field.
      * @param value The value of 'updatedBy'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setUpdatedBy(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.updatedBy = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedBy' field has been set.
      * @return True if the 'updatedBy' field has been set, false otherwise.
      */
    public boolean hasUpdatedBy() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'updatedBy' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearUpdatedBy() {
      updatedBy = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedTime' field.
      * @return The value.
      */
    public java.lang.Long getUpdatedTime() {
      return updatedTime;
    }

    /**
      * Sets the value of the 'updatedTime' field.
      * @param value The value of 'updatedTime'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setUpdatedTime(java.lang.Long value) {
      validate(fields()[16], value);
      this.updatedTime = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedTime' field has been set.
      * @return True if the 'updatedTime' field has been set, false otherwise.
      */
    public boolean hasUpdatedTime() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'updatedTime' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearUpdatedTime() {
      updatedTime = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.content = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearContent() {
      content = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'md5' field.
      * @return The value.
      */
    public java.lang.CharSequence getMd5() {
      return md5;
    }

    /**
      * Sets the value of the 'md5' field.
      * @param value The value of 'md5'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder setMd5(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.md5 = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'md5' field has been set.
      * @return True if the 'md5' field has been set, false otherwise.
      */
    public boolean hasMd5() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'md5' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSource.Builder clearMd5() {
      md5 = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FDDEIPSource build() {
      try {
        FDDEIPSource record = new FDDEIPSource();
        record.messageGUID = fieldSetFlags()[0] ? this.messageGUID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.transportGUID = fieldSetFlags()[1] ? this.transportGUID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bhsGUID = fieldSetFlags()[2] ? this.bhsGUID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.batchPosition = fieldSetFlags()[3] ? this.batchPosition : (java.lang.Long) defaultValue(fields()[3]);
        record.fhsGUID = fieldSetFlags()[4] ? this.fhsGUID : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.sender = fieldSetFlags()[6] ? this.sender : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.condition = fieldSetFlags()[7] ? this.condition : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.messageCode = fieldSetFlags()[8] ? this.messageCode : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.triggerEvent = fieldSetFlags()[9] ? this.triggerEvent : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.messageStructure = fieldSetFlags()[10] ? this.messageStructure : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.profile = fieldSetFlags()[11] ? this.profile : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.versionId = fieldSetFlags()[12] ? this.versionId : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.createdBy = fieldSetFlags()[13] ? this.createdBy : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.createdTime = fieldSetFlags()[14] ? this.createdTime : (java.lang.Long) defaultValue(fields()[14]);
        record.updatedBy = fieldSetFlags()[15] ? this.updatedBy : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.updatedTime = fieldSetFlags()[16] ? this.updatedTime : (java.lang.Long) defaultValue(fields()[16]);
        record.content = fieldSetFlags()[17] ? this.content : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.md5 = fieldSetFlags()[18] ? this.md5 : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FDDEIPSource>
    WRITER$ = (org.apache.avro.io.DatumWriter<FDDEIPSource>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FDDEIPSource>
    READER$ = (org.apache.avro.io.DatumReader<FDDEIPSource>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
