/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.cdc.ncezid.eip.ds.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FDDEIPSourceKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2536796357499468858L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FDDEIPSourceKey\",\"namespace\":\"gov.cdc.ncezid.eip.ds.schema\",\"fields\":[{\"name\":\"messageGUID\",\"type\":\"string\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FDDEIPSourceKey> ENCODER =
      new BinaryMessageEncoder<FDDEIPSourceKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FDDEIPSourceKey> DECODER =
      new BinaryMessageDecoder<FDDEIPSourceKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FDDEIPSourceKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FDDEIPSourceKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FDDEIPSourceKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FDDEIPSourceKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FDDEIPSourceKey from a ByteBuffer. */
  public static FDDEIPSourceKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence messageGUID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FDDEIPSourceKey() {}

  /**
   * All-args constructor.
   * @param messageGUID The new value for messageGUID
   */
  public FDDEIPSourceKey(java.lang.CharSequence messageGUID) {
    this.messageGUID = messageGUID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageGUID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageGUID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messageGUID' field.
   * @return The value of the 'messageGUID' field.
   */
  public java.lang.CharSequence getMessageGUID() {
    return messageGUID;
  }

  /**
   * Sets the value of the 'messageGUID' field.
   * @param value the value to set.
   */
  public void setMessageGUID(java.lang.CharSequence value) {
    this.messageGUID = value;
  }

  /**
   * Creates a new FDDEIPSourceKey RecordBuilder.
   * @return A new FDDEIPSourceKey RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder newBuilder() {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder();
  }

  /**
   * Creates a new FDDEIPSourceKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FDDEIPSourceKey RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder newBuilder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder other) {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder(other);
  }

  /**
   * Creates a new FDDEIPSourceKey RecordBuilder by copying an existing FDDEIPSourceKey instance.
   * @param other The existing instance to copy.
   * @return A new FDDEIPSourceKey RecordBuilder
   */
  public static gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder newBuilder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey other) {
    return new gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder(other);
  }

  /**
   * RecordBuilder for FDDEIPSourceKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FDDEIPSourceKey>
    implements org.apache.avro.data.RecordBuilder<FDDEIPSourceKey> {

    private java.lang.CharSequence messageGUID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FDDEIPSourceKey instance
     * @param other The existing instance to copy.
     */
    private Builder(gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'messageGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageGUID() {
      return messageGUID;
    }

    /**
      * Sets the value of the 'messageGUID' field.
      * @param value The value of 'messageGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder setMessageGUID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.messageGUID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageGUID' field has been set.
      * @return True if the 'messageGUID' field has been set, false otherwise.
      */
    public boolean hasMessageGUID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.eip.ds.schema.FDDEIPSourceKey.Builder clearMessageGUID() {
      messageGUID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FDDEIPSourceKey build() {
      try {
        FDDEIPSourceKey record = new FDDEIPSourceKey();
        record.messageGUID = fieldSetFlags()[0] ? this.messageGUID : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FDDEIPSourceKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<FDDEIPSourceKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FDDEIPSourceKey>
    READER$ = (org.apache.avro.io.DatumReader<FDDEIPSourceKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
