/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.cdc.ncezid.daas.event.hl7message.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class hl7messageKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2895149794183650650L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"hl7messageKey\",\"namespace\":\"gov.cdc.ncezid.daas.event.hl7message.schema\",\"fields\":[{\"name\":\"messageGUID\",\"type\":\"string\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<hl7messageKey> ENCODER =
      new BinaryMessageEncoder<hl7messageKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<hl7messageKey> DECODER =
      new BinaryMessageDecoder<hl7messageKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<hl7messageKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<hl7messageKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<hl7messageKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this hl7messageKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a hl7messageKey from a ByteBuffer. */
  public static hl7messageKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence messageGUID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public hl7messageKey() {}

  /**
   * All-args constructor.
   * @param messageGUID The new value for messageGUID
   */
  public hl7messageKey(java.lang.CharSequence messageGUID) {
    this.messageGUID = messageGUID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageGUID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageGUID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messageGUID' field.
   * @return The value of the 'messageGUID' field.
   */
  public java.lang.CharSequence getMessageGUID() {
    return messageGUID;
  }

  /**
   * Sets the value of the 'messageGUID' field.
   * @param value the value to set.
   */
  public void setMessageGUID(java.lang.CharSequence value) {
    this.messageGUID = value;
  }

  /**
   * Creates a new hl7messageKey RecordBuilder.
   * @return A new hl7messageKey RecordBuilder
   */
  public static gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder newBuilder() {
    return new gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder();
  }

  /**
   * Creates a new hl7messageKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new hl7messageKey RecordBuilder
   */
  public static gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder newBuilder(gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder other) {
    return new gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder(other);
  }

  /**
   * Creates a new hl7messageKey RecordBuilder by copying an existing hl7messageKey instance.
   * @param other The existing instance to copy.
   * @return A new hl7messageKey RecordBuilder
   */
  public static gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder newBuilder(gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey other) {
    return new gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder(other);
  }

  /**
   * RecordBuilder for hl7messageKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<hl7messageKey>
    implements org.apache.avro.data.RecordBuilder<hl7messageKey> {

    private java.lang.CharSequence messageGUID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing hl7messageKey instance
     * @param other The existing instance to copy.
     */
    private Builder(gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.messageGUID)) {
        this.messageGUID = data().deepCopy(fields()[0].schema(), other.messageGUID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'messageGUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageGUID() {
      return messageGUID;
    }

    /**
      * Sets the value of the 'messageGUID' field.
      * @param value The value of 'messageGUID'.
      * @return This builder.
      */
    public gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder setMessageGUID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.messageGUID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageGUID' field has been set.
      * @return True if the 'messageGUID' field has been set, false otherwise.
      */
    public boolean hasMessageGUID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageGUID' field.
      * @return This builder.
      */
    public gov.cdc.ncezid.daas.event.hl7message.schema.hl7messageKey.Builder clearMessageGUID() {
      messageGUID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public hl7messageKey build() {
      try {
        hl7messageKey record = new hl7messageKey();
        record.messageGUID = fieldSetFlags()[0] ? this.messageGUID : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<hl7messageKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<hl7messageKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<hl7messageKey>
    READER$ = (org.apache.avro.io.DatumReader<hl7messageKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
